%YAML:1.0
# data
# the tum dataset directory, change it to yours! 
dataset_dir: /path/to/dataset/Kitti/sequences/05

image_topic: /image_raw/compressed
depth_topic: /image_raw/depth

use_camera: 1

# camera intrinsics
camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

num_features: 150
num_features_init: 50
num_features_tracking: 50

display_width : 1024
display_height : 768
display_fx : 400
display_fy : 400
display_cx : 512
display_cy : 384

# left camera intrinsics
left_fx: 517.3
left_fy: 516.5
left_cx: 325.1
left_cy: 249.7
left_baseline: 0
left_x: 0
left_y: 0
left_z: 0

# right camera intrinsics
right_fx: 517.3
right_fy: 516.5
right_cx: 325.1
right_cy: 249.7
right_baseline: 0 
right_x: 0
right_y: 0
right_z: 0
